version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: omind-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
